### ISSUE TITLE
The NRLS will not be fronted by the SSP

### ISSUE THREAD

**Issue by wweatherill-answer** [nhsconnect/FHIR-NRLS-API#1]
After internal discussions within the NRLS team the decision to make explicit use of the NRLS has been revisited

It will no longer be the case that requests to read/write Pointers must first go through the SSP in order to reach NRLS

The reason being is that the NRLS does not need the majority of the features that the SSP provides such as routing and access control. Auditing is required as is access control however requirements around the latter are not yet clear. On this basis the decision has been made to remove the SSP dependency.

**Comment by swk003** [comment]
Agreed to remove SSP dependency from v2.1 of spec
