### ISSUE TITLE
Conformance | CapabilityStatement (API Definitions)

### ISSUE THREAD

**Issue by swk003** [nhsconnect/FHIR-NRLS-API#14]
https://nhsconnect.github.io/FHIR-NRLS-API/api_foundation_conformance.html

The sentance "All requests SHALL contain a valid ‘Authorization’ header and SHALL contain an ‘Accept’ header with at least one of the following application/json+fhir or application/xml+fhir." should be two seperate lines as it combines two requirments.

The mime types listed are also incorrect, the STU3 required mime types are, the fhir is at the front not the type now:

    XML: application/fhir+xml
    JSON: application/fhir+json

It is also advised that the servers supports DSTU2 MIME-types for backwards compatibility where xml and json come before the fhir:

    XML: application/xml+fhir
    JSON: application/json+fhir

It is recomended that the server shall also graceful handling generic XML and JSON MIME types:

    XML: application/xml
    JSON: application/json
    JSON: text/json

In addition review:
https://nhsconnect.github.io/FHIR-NRLS-API/api_foundation_conformance.html#2-example

**Comment by briandiggle** [comment]
GP Connect has similar guidance as that suggested here which we formulated recently.

There are discussions about  common guidance which applies to NHS FHIR APIs in one (non-programme specific) place. Feels like this a good example of such common guidance  - to avoid divergence and align towards the coming strategic authZ and authN implementation.

**Comment by swk003** [comment]
The above mime type guidance is specified in the capability statement guidance documentation - I am looking for a home for this and have requested (for now) that it sits within the FHIR Policy pack.
