### ISSUE TITLE
Test Overview

### ISSUE THREAD

**Issue by swk003** [nhsconnect/FHIR-NRLS-API#17]
https://nhsconnect.github.io/FHIR-NRLS-API/test.html - 

This seems a bit confused, is this testing for the NRLS or for consumers/providers (who are actually also consumers of the NRLS).

**Comment by wilkinsm** [comment]
Speaking with Will, the current content needs to be removed and replaced with TBC placeholder as the details of testing are still under discussion.

**Comment by swk003** [comment]
Track DDP-154

**Comment by wilkinsm** [comment]
Thanks,  just waiting on access to the board.

**Comment by swk003** [comment]
added under construction script
