### ISSUE TITLE
Transport Layer Security (TLS) and Supported Ciphers

### ISSUE THREAD

**Issue by swk003** [nhsconnect/FHIR-NRLS-API#18]
DDC confirmed that TLSv1.2 must be supported for all new Spine interfaces.

DDC will also confirm/ provide the latest SSL supported cyphers.

Security section needs to be amended to reflect these Infrastructure Security, Operational Security and Spine DDC requirements.

In addition:
“Tomcat OpenSSL Support Using The APR/Native Provider” I don’t think Tomcat specifics are required?

**Comment by lwelch88** [comment]
Info from Conrad: The ciphers that need to be used for all new interfaces are AESGCM+EECDH, AESGCM+EDH, AES256+EECDH, AES256+EDH and TLS1.2 need to be used.

**Comment by wilkinsm** [comment]
Done, awaiting Jira Review.

**Comment by wilkinsm** [comment]
Ciphers  updated. Tomcat specifics removed. Reviewed and approved. Now closing.

**Comment by swk003** [comment]
What is reason behind removal of Tomcat OpenSSL ?

**Comment by wilkinsm** [comment]
That section was highlighted above. The reason behind removal is the fact that detailing Tomcat is technology specific and gives an impression of required/preferred technologies which is not the case. It could just as well be that IIS or Nginx is detailed.

Looking back on [that page](https://nhsconnect.github.io/FHIR-NRLS-API/development_api_security_guidance.html) it could be argued that yellow notice banner containing 'A Java 8 (or above) Runtime Environment....' is too 'technology specific/biased'.

**Comment by swk003** [comment]
That seems reasonable. The Tomcat stuff was cribbed from GPC I think!
