### ISSUE TITLE
Record retrieval via the SSP will not be mandated

### ISSUE THREAD

**Issue by wweatherill-answer** [nhsconnect/FHIR-NRLS-API#2]
Currently the NRLS specification 2.0.0-alpha.1 states that when a Consumer wishes to follow a Pointer to retrieve a Record the SSP will mediate the retrieval.

This restriction will be removed. Instead Providers can elect to create Pointers that do not involve the SSP. In some circumstances it may form part of the contract of Record retrieval that the SSP is involved for example as in the case of GPConnect. However the NRLS will not mandate that a Provider must involve the SSP in the exposure of their Records.

At the moment how a Consumer would use a Pointer to retrieve the Record that it points to is not clear in the spec.

A new section should be added to the "Solution" section to explain how the NRLS project envisages that Records can be retrieved.

**Comment by wilkinsm** [comment]
Places that require updates regarding this issue:

- https://nhsconnect.github.io/FHIR-NRLS-API/overview_behaviours.html#record-retrieval-by-consumers
- http://127.0.0.1:4006/overview_interactions.html#interactions

**Comment by wweatherill-answer** [comment]
Closed as this issue has been addressed in version 2.3.0 of the specification.
