### ISSUE TITLE
Dev Guidance Section

### ISSUE THREAD

**Issue by swk003** [nhsconnect/FHIR-NRLS-API#27]
Feedback on Development Overview section. Needs review:

2. Pre-Requisites for NRLS API

Are these pre-requisites on the actual Spine NRLS server API, or on connecting systems?

“SHALL support XML or JSON formats for all API interactions.” Should this be MUST, and should it be both not or?

2.2 FHIR Conformance

Must client systems (Providers and Consumers) also provide a Capability resource?

Think the link to “…see also NRLS API FHIR conformance profile.” should be called Capability rather than Conformance.

2.3 Spine Services

Should “And pass this user information in a JSON web token…” be un-indented as it applies to both of the either clauses?

**Comment by wweatherill-answer** [comment]
>Are these pre-requisites on the actual Spine NRLS server API, or on connecting systems?
At the moment this section feels a little mixed in terms of content (ie NRLS server vs client pre-reqs living in the same list). 

This spec is meant to be guidance for people who want to develop against the NRLS therefore pre-reqs should be written from that perspective.

>“SHALL support XML or JSON formats for all API interactions.” Should this be MUST, and should it be both not or?
This is an example of a client pre-req and it's where the section is a little mixed in terms of it's content. From a client perspective this is correct; you must support at least one of XML or JSON but the server must support both.

>Must client systems (Providers and Consumers) also provide a Capability resource?
No. Just the server

>Think the link to “…see also NRLS API FHIR conformance profile.” should be called Capability rather than Conformance.
Agreed

>Should “And pass this user information in a JSON web token…” be un-indented as it applies to both of the either clauses?
Agreed

**Comment by swk003** [comment]
Fixed in Release 2.3.0
