### ISSUE TITLE
Cross Organisation Audit & Provenance/ JSON Web Tokens (JWT)

### ISSUE THREAD

**Issue by swk003** [nhsconnect/FHIR-NRLS-API#28]
JSON Web Tokens (JWT)

We need to centralise / genericise the JWT creation and checking, shouldn’t need to be part of an API spec.

Are these claims correct and complete?

In addition:
I think we need to move to signed JWTs before we can put patient data into this?

**Comment by wweatherill-answer** [comment]
NHS D are keen to converge on a single standard for the claims and scopes in these tokens, which are currently defined in a number of different API specs. To that end the various API streams will be coming together in mid-Jan to begin the process of rationalising a JWT structure.
