### ISSUE TITLE
Spine Security Proxy (SSP) Section

### ISSUE THREAD

**Issue by swk003** [nhsconnect/FHIR-NRLS-API#29]
https://nhsconnect.github.io/FHIR-NRLS-API/integration_spine_security_proxy.html

I think this is a separate product / service that should be specified elsewhere.

2017-12-20 Request from Hadleigh:
I can see the SSP page of the spec is empty – do we not have enough info to be able to put something on there about it for sprint 2? Andy Q is the PM who will be looking after this for us – so I am sure from a generic overview perspective we should be able to pull something together fairly soon.

2017-12-20 swk003 response: 

The dedicated SSP section has yo-yoed in and out of spec already. There is sub-section in Solution overview behaviours that introduces the proposed capabilities of the SSP in NRLS. We have a couple of SSP issues on the backlog that need to be discussed. We can add these to Sprint 2….however we need to be clear on the strategy for provider pointer control and consumer retrieval mechanisms before this can be fully specified. We will aim to include an updated SSP functionality in Sprint 2 release.

**Comment by wweatherill-answer** [comment]
The part that the SSP has to play in the NRLS solution has been documented in a section called "Record Retrieval by Consumers" - https://developer.nhs.uk/apis/nrls/overview_behaviours.html
