### ISSUE TITLE
Provider API (Release: NRLS 2.2.0-alpha)

### ISSUE THREAD

**Issue by swk003** [nhsconnect/FHIR-NRLS-API#35]
1. Create/ Delete operations specify: 'The type data-element MUST be included in the payload request'. The type element is a mandatory core DocumentReference element. It also duplicates API Guidance reference section/ profile elements mapping to solution data model. This constraint does not need to be re-enforced in Provider API section.

2. Sect 2 Provider Search states 'API to support pointer owner (custodian) searches based on ODS code'.  Provider (Pointer owner)  searches have now been aligned with Consumer searches to support ODS + NHS#. This needs to be amended to reflect change. 

3. Sect 2.3 Search Parameters: _count is a FHIR 'search result parameter' and not a specific DocumentReference search param  - it needs to be in its own section

4. Sect 2.3 Search Parameters: Search combos conformance could be amended to state 'Search based on at least 1 of 'custodian' or 'subject' documentReference elements.

5. Sect 2.3 Search Parameters: Could include an example combination query **SK closed in NRLS 2.4.0-alpha**

6. Sect 2.3.3. _count: References 'See Managing Returned Resources for details on these parameters.' Perhaps we could be more specific and state that this is a FHIR 'search result parameter'.

7. Sect 2.3.3. _count: Note: If the _count parameter is included then the resulting Bundle that is returned may include page navigation links where appropriate. This should be in Section: 2.4 Search Response

8. Sect 2.3.3. _count: is the _count a 'SHOULD' conformance parameter? **Fixed in 2.3.0**

9. There are no examples - needs to be added

10. Sect 3.2. Provider Create Operation is missing an create URL example

**Comment by wilkinsm** [comment]
With regards to **point 1**:

It was suggested that Type should be highlighted in the spec with regards to the constraint on using  SNOMED instead of the base DocRef which states LONIC.

I believe the aim of this highlight is to state which **controlled set** should be used. 

Once confirmed we could alter this section to highlight this.

**Comment by DamianJMurphy** [comment]
LOINC was recently rejected by DSAS as a suitable standard for NHS use. That was principally aimed at pathology reporting, but the rejection was supported by NHS Digital's Information Representation team and by PRSB amongst others.

**Comment by swk003** [comment]
The spec references the NRLS-DocumentReference-1 FHIR profile: https://fhir.nhs.uk/STU3/StructureDefinition/NRLS-DocumentReference-1. It is constrained to SNOMED. There is no reference to LOINC  terminology.

**Comment by wilkinsm** [comment]
I'm under the impression that this all stems from the different between the NRLS Document Reference and the base [FHIR Document Reference](https://www.hl7.org/fhir/STU3/documentreference.html) where it does mention LOINC.
