### ISSUE TITLE
Consumer API (Release: NRLS 2.2.0-alpha)

### ISSUE THREAD

**Issue by swk003** [nhsconnect/FHIR-NRLS-API#36]
1. Sect 2.3 Search Parameters: _count is a FHIR 'search result parameter' and not a specific DocumentReference search param  - it needs to be in its own section

2. Sect 2.3 Search Parameters: Search combos conformance could be amended to state 'Search based on at least 1 of 'custodian' or 'subject' documentReference elements.

3. Sect 2.3 Search Parameters: Could include an example combination query **SK closed in NRLS 2.4.0-alpha**

4. Sect 2.3.3. _count: References 'See Managing Returned Resources for details on these parameters.' Perhaps we could be more specific and state that this is a FHIR 'search result parameter'.

5. Sect 2.3.3. _count: Note: If the _count parameter is included then the resulting Bundle that is returned may include page navigation links where appropriate. This should be in Section: 2.4 Search Response

6. Sect 2.3.3. _count: is the _count a 'SHOULD' conformance parameter? **SK closed in NRLS 2.3.0-alpha**

7.  Sect 2.5.1 Request Query: the example includes the 'created' parameter. This is out of scope for this release.

8. Sect 2.5.2 cURL. example params dont match search section **SK closed in NRLS 2.4.0-alpha**

9. Sect 2.5.3 Query Response Http Headers: There are no examples/ [TODO Response] - needs to be completed. **SK closed in NRLS 2.4.0-alpha**

10. Sect 2.3.2. subject
**Added from https://github.com/nhsconnect/FHIR-NRLS-API/issues/30**
 Not sure what “This SHALL be supported for all consumer systems.” means here. Are we saying that spine SHALL accept and process this parameter, or that Consumer systems SHALL send it? If it’s the former, then an IG isn’t (in my opinion / experience) the best way to describe hard requirements to DDC. If it’s the latter than I don’t know why we’re dictating that they must do this? **SK: This para has been removed from Consumer and Provider API.**

**Comment by wweatherill-answer** [comment]
1. After internal review the decision has been taken to leave this param in with the other params to keep the documentation as simple and light as we can. In the future if we have more non-DocRef based params we will consider breaking them out into a separate area if there is a need to.

**Comment by wweatherill-answer** [comment]
2. Section 2.3 from https://nhsconnect.github.io/FHIR-NRLS-API/api_consumer_documentreference.html does state the one or both of patient and/or custodian should be provided so the spec is clear in terms of the expected behaviour. The point really comes down to how that info is presented. In the future the NRLS may revisit how this info is presented to make it fall in line with other NHS D specs such as careconnect.
