### ISSUE TITLE
Count should not be a mandatory param when performing a search

### ISSUE THREAD

**Issue by lwelch88** [nhsconnect/FHIR-NRLS-API#38]
- Comment from Adam H - 

> On paging - we've said that specifying a count request parameter is a SHOULD - is there a reason this isn't just a MAY/COULD? Presumably we will have a default page size, so recommending that all clients provide their own count values seems unnecessary, and could make volumetrics more difficult to predict as each client could request different size pages?

**Comment by lwelch88** [comment]
If the user issues a request without specifying a count (ie a non-paged request) but the number of results in the result-set is greater than some threshold (to be determined) then the server will limit the number of results that come back effectively returning a page to a non-page request.

**Comment by wweatherill-answer** [comment]
This feedback has been incorporated into the most recent release of the spec (2.3.0 - https://developer.nhs.uk/apis/nrls/) therefore closing ticket.
