### ISSUE TITLE
The NRLS needs to describe an Auditing capability

### ISSUE THREAD

**Issue by wweatherill-answer** [nhsconnect/FHIR-NRLS-API#4]
The specification (2.0.0-alpha.1) current relies on the SSP to perform auditing (see #1). Given that this dependency will be removed the NRLS spec needs to make mention of the fact that Auditing will be performed on Pointer read and write.

**Comment by ahatherly** [comment]
For national services we had previously agreed that the SSP would not be used. I'd suggest you start from the content in the V&M API spec which outlines the expectations around audit using a JWT (which should be identical to what SSP expects): https://developer.nhs.uk/apis/vandm/integration_cross_organisation_audit_and_provenance.html
Better still, if we can agree that we will make use of the strategic auth platform to authenticate and authorise access to NRLS (which would be ideal if possible), the access token would be given out by that service and the implementer could use that directly to gain access without having to either construct it manually as GP connect does (fudge), or configure a local OAuth solution to generate tokens that meet this format (with all the associated assurance overhead that would entail for us to trust it).

**Comment by wilkinsm** [comment]
A version of this currently exists at: https://nhsconnect.github.io/FHIR-NRLS-API/integration_cross_organisation_audit_and_provenance.html

**Comment by wweatherill-answer** [comment]
Following internal conversations within the NRLS team where Information Governance advice was given the following statements capture the kind of information that will be audited

Request
_"This local user on this system from this organisation with this legitimate relationship has sent this payload at this time..."_

alternatively depending on the authentication mechanism that is eventually used with NRLS the above could be re-written as
_"This nationally authenticated user on this system  from this organisation with this legitimate relationship has sent this payload at this time..."_

Response
_"...which resulted in this response being returned"_

There will need to be a way to tie the request and response audit records together so that a request/response interaction can be traced. 
In addition the response should not be a reference to the Pointers that have been returned by instead should be the actual Pointer values to account for the fact that a given Pointer's contents can evolve over time.

The current thinking is that the audit compoenents in terms of the request should be put in a JWT as a series of claims

Purpose of request (i.e. legitimate relationship)
Username - local system user name
ASID - local system ID
Organisation - ODS code
Patient - the Patient whose details are being requested. Note that in some circumstances this may not have been supplied. For example it is possible to search the NRLS for all Pointers that are maintained by a given organisation
Interaction ID - the kind of action that was being requested (eg query of the NRLS of modification of the NRLS)
