### ISSUE TITLE
Consider expanding the JWT to support a more secure Provider read operation

### ISSUE THREAD

**Issue by wweatherill-answer** [nhsconnect/FHIR-NRLS-API#5]
The NRLS specification (2.0.0-alpha.1) states that a Provider should only be able to search for Pointers that they own. At the moment the ODS code of the owning org is one of the search params. It is not clear how the NRLS will verify that this ODS code belongs to the Provider making the request.

Consider removing this param from the search and instead adding an Organisation to the JWT (similar to GPConnect). The expectation is that the JWT would be validated to ensure that the Org matches the Provider making the request (eg perhaps by cross referencing the client's certificate to the assigned ODS code). If so then that ODS code is used to drive the search. If not the NRLS returns an error (TBD) stating that there is a problem with the request.

This also has the advantage that the NHS number of a patient could be made an optional param allowing a Provider to see all Pointers that they own for a given Patient allowing them to easily support Patient opt-out or mass deletion of a Patient's Pointers for some other reason.

**Comment by ahatherly** [comment]
The plan was to separate out common national API functionality such as the JWT definition into it's own specification pack to reduce duplication, align better with what is implemented in Spine and Strategic Auth, and prevent programmes from diverging. I don't think that new common spec has been drafted yet, but when it is we'll probably need to refactor the NRLS spec to reference it accordingly.

**Comment by wweatherill-answer** [comment]
The NRLS will no longer specify that a Provider can only search for Pointers that they own therefore the justification for this issue no longer exists - closing this ticket on that basis.

**Comment by swk003** [comment]
Has justification for this reversal been documented yet?

**Comment by wweatherill-answer** [comment]
The decision to remove this functionality is a natural consequence of the decision to unify the Provider and Consumer search functionality (see #20 for more detail on the background to this decision). 

Given that there will no longer be separate search APIs for Consumers and Providers capturing the ODS code in the JWT is no longer supporting any functionality therefore to keep the API as lean as possible the decision was taken to remove it from the JWT.
