### ISSUE TITLE
Consumer API: Patient Search Path

### ISSUE THREAD

**Issue by swk003** [nhsconnect/FHIR-NRLS-API#8]
Section 1.3 table: The patient search path should be 'DocumentReference.patient(Patient)'.

**Comment by wilkinsm** [comment]
To follow a standard as per [Issue #9 ](https://github.com/nhsconnect/FHIR-NRLS-API/issues/9), the search path should remain as:

> DocumentReference.subject (Patient)

This is inline with the path as is in the [Structured Definition](https://fhir.nhs.uk/STU3/StructureDefinition/NRLS-DocumentReference-1)

It would then also be more accurate to change the parameter name from patient to **subject**.

**Comment by swk003** [comment]
On reflection, I think the  patient search parameter table is spot on. I think it can be left as is....
![image](https://user-images.githubusercontent.com/8655284/34262705-06fc4cd0-e665-11e7-9260-d14c2fb77f0b.png)

**Comment by wilkinsm** [comment]
Should the parameter name be changed to **subject**?

This would put it in line with the parameter in the following table: https://nhsconnect.github.io/FHIR-NRLS-API/api_provider_documentreference.html#23-search-parameters

**Comment by wilkinsm** [comment]
We have agreed to change the parameter to **subject** for consistency within the API. i.e. Search parameter names will match DocumentReference elements.

This issue will remain open as we are going to seek guidance on the correctness of the parameter name to determine whether **patient** or **subject** is correct.

**Comment by swk003** [comment]
We need to be clear on search scope. If reference scope is intended to support Practitioner, Group, Patient types etc then 'subject' param should be used, however if limited to only include references of type patient then the 'patient' param should be used - see http://hl7.org/fhir/STU3/search.html#reference. 

Different ways of searching for resources associated with a patient usually depends on context and implementation. US-Core, MHD and CareConnect specs all explicitly use 'patient' param to search for resources associated to a specific patient. US-Core also highlights a number of different legal variations mostly using the subject param. Should Spine support all these variations?

Whatever syntax we agree, I think the key Q is actually whether we should be specifying a synthesised literal identifier as proposed by NDOP i.e. https://demographics.spineservices.nhs.uk/STU3/Patient/6105551233. 

I think this needs more discussion with DIP architects...... @TimCoates @ahatherly can you add to this?

**Comment by swk003** [comment]
Agreed to use patient parameter + literal reference: https://demographics.spineservices.nhs.uk/STU3/Patient/6105551233

**Comment by wweatherill-answer** [comment]
Closed based on agreement to use patient "synthetic" param.
