### ISSUE TITLE
Provider API: Custodian Search Path

### ISSUE THREAD

**Issue by swk003** [nhsconnect/FHIR-NRLS-API#9]
https://nhsconnect.github.io/FHIR-NRLS-API/api_provider_documentreference.html#221-search-parameters - Search parameters don't match the example request. Also the provider search does not state that the providers have to search for documents which they are custodians for so in theory they could get documents for other organisations. Would it be better to use the requesting organisation in the JWT to restrict the document references they can see.

Section 2.3 table: The organization search path should be 'DocumentReference.custodian(Organization)'.

**Comment by wilkinsm** [comment]
This has been completed and reviewed.
